### ISSUE TITLE
build system relies on ocaml-protoc for ocamlbuild dependency

### ISSUE THREAD

**Issue by mransan** [Khady/ocamlbuild-protoc#1]
See https://github.com/Khady/ocamlbuild-protoc/blob/master/opam#L16 `ocamlbuild` is missing and now that ocaml-protoc has switched to dune it no longer depends on ocamlbuild.

**Comment by Khady** [comment]
I aded https://github.com/Khady/ocamlbuild-protoc/commit/1a469214ac6a772dc272fbcb57916f3d3faf560a and I see that the package description was updated in opam. So now it should all be good? Thanks for pinging me.

**Comment by mransan** [comment]
Awesome! Thanks
